version: '3.8'

services:
  web:
    build: .
    command: python3 app/main.py
    volumes:
      - .:/app
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=parser_user
      - POSTGRES_PASSWORD=parser_pass
      - POSTGRES_DB=parser_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  postgres_data: